configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/runwayml%2Frunwayml-9cf1febc614000f72d4332f8bee51b6873b6bce49c9bdc02daae300e6882f9dd.yml
openapi_spec_hash: 03bc8d7e2d182e5a9aa9fdb7ca4f4e07
config_hash: b98eed33f1bba05e3c2a3e20d85d582a
