configured_endpoints: 15
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/runwayml%2Frunwayml-f33cb61dbbf6fbd1cce4b89a4512eb8bcc117e7b68db0624ff24a1c479a9718d.yml
openapi_spec_hash: 65fd21eeb0a1bb7145a3b02077ca3e8f
config_hash: b98eed33f1bba05e3c2a3e20d85d582a
