configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/runwayml%2Frunwayml-7224ebbce027b1fc6f3ee5c2428373e7b9a95a10145beff6eec5569b5bd87457.yml
openapi_spec_hash: aa1a352fdb61e6cc76cfb152fba9ee82
config_hash: 047ba0ba39c5c504cd4cdf7daa217a1d
